jewelryshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

# To display images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'store'

urlpatterns = [
    path('', views.home, name="home"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('orders/', views.orders, name="orders"),
    path('checkout/', views.checkout, name="checkout"),
    path('about_us/', views.about_us, name="about_us"),

    # URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('store/contact_us/', views.ContactUsView.as_view(), name='contact_us'),
    path('store/cust_messages/', views.cust_messages, name="cust_messages"),
    path('store/cust_returns/', views.cust_returns, name="cust_returns"),
    path('store/policy/', views.policy, name="policy"),
    path('store/faq/', views.faq, name="faq"),

    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),


]

store/forms.py
from django.contrib.auth import password_validation
from .models import Address, Contact_Us
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.db import models
from django.db.models import fields
from django.forms import widgets
from django.forms.fields import CharField
from django.utils.translation import gettext, gettext_lazy as _



class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        labels = {'email': 'Email'}
        widgets = {'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Username'})}


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}))


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['locality', 'city', 'state', 'country']
        widgets = {'locality':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Popular Place like Restaurant, Religious Site, etc.'}),
                   'city':forms.TextInput(attrs={'class':'form-control', 'placeholder':'City'}),
                   'state':forms.TextInput(attrs={'class':'form-control', 'placeholder':'State or Province'})}


class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'auto-focus':True, 'class':'form-control', 'placeholder':'Current Password'}))
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control', 'placeholder':'New Password'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control', 'placeholder':'Confirm Password'}))


class PasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label=_("Email"), max_length=254, widget=forms.EmailInput(attrs={'autocomplete':'email', 'class':'form-control'}))


class SetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'form-control'}))


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact_Us
        fields = ['firstname', 'lastname', 'email', 'phone', 'message']
        widgets = {'firstname':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter First Name Here'}),
                   'lastname':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Last Name Here'}),
                   'email':forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter Email Here', 'autocomplete':'email'}),
                   'phone':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Phone Number Here'}),
                   'message':forms.Textarea(attrs={'class':'form-control', 'placeholder': 'Tell Us How We Can Help'}),}

store/views.py
import django
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator
from django.views import View
from django.shortcuts import redirect, render, get_object_or_404
from .models import Address, Cart, Category, Order, Product, Contact_Us
from .forms import RegistrationForm, AddressForm, ContactForm
import decimal
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator  # for Class Based Views
from django.urls import reverse_lazy


# Create your views here.

def home(request):
    categories = Category.objects.filter(is_active=True, is_featured=True)[:3]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    context = {
        'categories': categories,
        'products': products,
    }
    return render(request, 'store/index.html', context)


def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    related_products = Product.objects.exclude(id=product.id).filter(is_active=True, category=product.category)
    context = {
        'product': product,
        'related_products': related_products,
    }
    return render(request, 'store/detail.html', context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'store/categories.html', {'categories': categories})


def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(is_active=True, category=category)
    categories = Category.objects.filter(is_active=True)
    context = {
        'category': category,
        'products': products,
        'categories': categories,
    }
    #paginator = Paginator(products, 12)
    #page_number = request.GET.get('page')
    #page_obj = paginator.get_page(page_number)
    return render(request, 'store/category_products.html', context)
    #return render(request, 'store/category_products.html', {'products': products, 'page_obj': page_obj})


class ContactUsView(View):
    def get(self, request):
        form = ContactForm
        return render(request, 'store/contact_us.html', {'form': form})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'store/confirmation.html')


# Authentication Starts Here

class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'account/register.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            messages.success(request, "Congratulations! Registration Successful!")
            form.save()
        return render(request, 'account/register.html', {'form': form})


@login_required
def profile(request):
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, 'account/profile.html', {'addresses': addresses, 'orders': orders})


@method_decorator(login_required, name='dispatch')
class AddressView(View):
    def get(self, request):
        form = AddressForm()
        return render(request, 'account/add_address.html', {'form': form})

    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            user = request.user
            locality = form.cleaned_data['locality']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            reg = Address(user=user, locality=locality, city=city, state=state)
            reg.save()
            messages.success(request, "New Address Added Successfully.")
        return redirect('store:profile')


@login_required
def remove_address(request, id):
    a = get_object_or_404(Address, user=request.user, id=id)
    a.delete()
    messages.success(request, "Address removed.")
    return redirect('store:profile')


@login_required
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    # Check whether the Product is already in Cart or Not
    item_already_in_cart = Cart.objects.filter(product=product_id, user=user)
    if item_already_in_cart:
        cp = get_object_or_404(Cart, product=product_id, user=user)
        cp.quantity += 1
        cp.save()
    else:
        Cart(user=user, product=product).save()

    return redirect('store:cart')


@login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)

    # Display Total on Cart Page
    amount = decimal.Decimal(0)
    shipping_amount = decimal.Decimal(0)
    # using list comprehension to calculate total amount based on quantity and shipping
    cp = [p for p in Cart.objects.all() if p.user == user]
    if cp:
        for p in cp:
            temp_amount = (p.quantity * p.product.price)
            amount += temp_amount

    # Customer Addresses
    addresses = Address.objects.filter(user=user)

    context = {
        'cart_products': cart_products,
        'amount': amount,
        'total_amount': amount + shipping_amount,
        'addresses': addresses,
    }
    return render(request, 'store/cart.html', context)


@login_required
def remove_cart(request, cart_id):
    if request.method == 'GET':
        c = get_object_or_404(Cart, id=cart_id)
        c.delete()
        messages.success(request, "Product removed from Cart.")
    return redirect('store:cart')


@login_required
def plus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        cp.quantity += 1
        cp.save()
    return redirect('store:cart')


@login_required
def minus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        # Remove the Product if the quantity is already 1
        if cp.quantity == 1:
            cp.delete()
        else:
            cp.quantity -= 1
            cp.save()
    return redirect('store:cart')


@login_required
def checkout(request):
    user = request.user
    amount = decimal.Decimal(0)
    total_amount = decimal.Decimal(0)
    addresses = Address.objects.filter(user=user).first()
    cart_products = Cart.objects.filter(user=user)

    cp = [p for p in Cart.objects.all() if p.user == user]
    if cp:
        for p in cp:
            amount = (p.quantity * p.product.price)
            total_amount += amount
    context = {
        'cart_products': cart_products,
        'amount': amount,
        'total_amount': total_amount,
        'addresses': addresses,
    }
    return render(request, 'store/checkout.html', context)


@login_required
def orders(request):
    user = request.user
    cart = Cart.objects.filter(user=user)
    addresses = Address.objects.filter(user=user).first()
    for c in cart:
        # Saving all the products from Cart to Order
        Order(user=user, address=addresses, product=c.product, quantity=c.quantity).save()
        # And Deleting from Cart
        c.delete()
    all_orders = Order.objects.filter(user=request.user).order_by('-ordered_date')
    return render(request, 'store/orders.html', {'orders': all_orders})


def shop(request):
    return render(request, 'store/shop.html')


def test(request):
    return render(request, 'store/test.html')


@permission_required('view_messages', raise_exception=True)
def cust_messages(request):
    all_messages = Contact_Us.objects.all()
    return render(request, 'store/cust_messages.html', {'all_messages': all_messages})


def cust_returns(request):
    return render(request, 'store/cust_returns.html')


def policy(request):
    return render(request, 'store/policy.html')


def faq(request):
    return render(request, 'store/faq.html')


def about_us(request):
    return render(request, 'store/about_us.html')

templates/store/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container py-3">
        <row>
            <div class="img-fluid" ><img src="{% static 'img/about_us_2.jpg' %}" alt="picture 1" style="width: 100%"> </div>
        </row>
        <hr>
        <h2 class="mb-5" style="text-align: center; padding-top: 25px; font-weight: normal">ABOUT DESI CHAMAK</h2>
        <p class="text-center">Desi Chamak is a local retail company that sells South Asian accessories. The company
            sells its products online to customers worldwide.</p>
        <hr>
        <div class="text-decoration-underline">
           <h4 class="text-center text-uppercase" style="font-weight: normal">Who Are We?</h4>
           <br>
	</div>
        <div class="d-flex justify-content-around" style="font-size: 1.1em; font-weight: bold">
            <span>Sukhpreet Singh</span> <span>Nirvana Sharma Singh</span> <span>Gurpreet Singh</span>
        </div>
        <div class="text-center">
            <br>
            <p>Greetings! We are three best friends that have started a flourishing local business in Virginia,
                USA known as Desi Chamak.</p>
            <p>Growing up, we used to perform in the same Bhangra team. Bhangra is a traditional folk dance of Punjab,
                that connected and led us to create a business that best represents South Asian culture. Our friendship
                blossomed and soon led us to be here and provide the best products to customers like you!</p>
            <p>In order to effectively advance the company to a higher and bigger platform, we have adopted numerous
                business growth strategies & techniques as a team throughout the years so you could have a user-friendly
                experience.</p>
        </div>
        <div class="text-decoration-underline">
            <h4 class="text-center text-uppercase" style="font-weight: normal">Mission</h4>
        </div>
        <div class="text-center">
            <p>Our mission is to offer the best customer satisfaction to people around the NOVA area with the best
                South Asian Jewelry. We thrive and aim to double our base of new customers worldwide.</p>
        </div>
        <div class="text-decoration-underline">
            <h4 class="text-center text-uppercase" style="font-weight: normal">Goal</h4>
        </div>
        <div class="text-center">
            <p>With our new Desi Chamak website, our goal is to overcome the business challenges that affect customer
                growth, customer satisfaction, and the visibility and modernism of the company. We have upgraded
                ourselves to bring Desi Chamak an online presence and automated our system to support customer needs and
                communication. Our effort is to provide the best shopping experience to not only domestic but also
                worldwide customers. In doing so, we are able to sell a higher quantity of products at an affordable
                price and deliver them to customers securely and free of shipping to those residing within the NOVA
                area.</p>
        </div>
        <div class="text-decoration-underline">
            <h4 class="text-center text-uppercase" style="font-weight: normal">OUR PRODUCTS</h4>
        </div>
        <div class="text-center">
        <p>India is acknowledged as the largest and best center for cutting diamonds and gems in the world. Not
            only is the nation unmatched at cutting gems, but it also excels at producing exceptional jewelry,
            whether it is fashioned by hand or with machinery.</p>
        <p>Desi Chamak provides Indian handmade jewelry to those interested. Our products are made from premium
            materials and are as elegant as they can be to promise a dashing look to those who wear them.</p>
        <p>Besides that, we also stock other pieces of fashion other than gold. We showcase different bundles of
            products across our website. Please feel free to check them out.</p>
        <p>If you have any concerns, feedback, or questions, please reach out to us on the <a href="{% url 'store:contact_us' %}">Contact Us</a> page.</p>
        <p>We thank you for choosing Desi Chamak!</p>
        </div>
    </div>

{% endblock content %}

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Cart</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cart</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

          {% include 'partials/_messages.html' %}

          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantity</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.png' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">${{cart_product.product.price}}</p>
                      </td>
                      <td class="align-middle border-0">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                          <div class="quantity">
                            <a href="{% url 'store:minus-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                            {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="{{cart_product.quantity}}"/>
                            {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                            <a href="{% url 'store:plus-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">${{cart_product.total_price|intcomma}}</p>
                      </td>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a></div>
                  <div class="col-md-6 text-md-right"><a class="btn btn-outline-dark btn-sm" href="{% url 'store:checkout' %}">Proceed to checkout<i class="fas fa-long-arrow-alt-right ml-2"></i></a></div>
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">Cart total</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">${{amount|intcomma}}</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Shipping Charge</strong><span class="text-muted small">+ $0.00</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>${{total_amount|intcomma}}</span></li>
                    <li>

                      {% comment %} <form action="#">
                        <div class="form-group mb-0">
                          <input class="form-control" type="text" placeholder="Enter your coupon">
                          <button class="btn btn-dark btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Apply coupon</button>
                        </div>
                      </form> {% endcomment %}

                    </li>
                  </ul>

                  
                  <h5 class="text-uppercase my-5">Select Shipping Address</h5>
                  
                  <form action="{% url 'store:checkout' %}" id="myform">

                    {% if addresses %}
                      {% for address in addresses %}
                        <div class="mb-3">
                        <input type="radio" name="address" value="{{address.id}}"> <strong>Address {{forloop.counter}}</strong> <br>
                        ( {{address.locality}}, {{address.city}}, {{address.state}} )
                        </div>
                      {% endfor %}
                    {% endif %}

                    <!-- Set up a container element for the button -->
                    <div class="text-end" id="paypal-button-container"></div>

                    {% comment %} For Cash on Delivery {% endcomment %}
                    <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" type="submit"> <i class="fas fa-dollar-sign mr-2"></i>Cash on Delivery</button>

                  </form>

                </div>
              </div>
            </div>

          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Your cart is empty.</h3>
            <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

      {% block payment-gateway %}
        <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=YOUR-PAYPAL-CLIENT-ID&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{total_amount}}'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    // Savind Order in Database after Payment Success
                    document.getElementById('myform').submit();
                });
            }


        }).render('#paypal-button-container');
    </script>
      {% endblock payment-gateway %}

templates/store/confirmation.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

            <h1 class="mb-5">Message Received</h1>


            <div class="card mb-4">
              <div class="card-header">
                <p>Thank You for Reaching Out! We will get back to shortly</p>
              </div>
              <div class="card-body">
                  <a href="{% url 'store:all-categories' %}">Continue Shopping...</a>
              </div>
            </div>
        </div>
      </div>
    {% endblock content %}

templates/store/cust_messages.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-3">
        <h1 class="mb-5">All Messages</h1>

        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <th>Date Entered</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Message</th>
                </thead>
                {% for message in all_messages %}
                    <tr>
                        <td>{{ message.created_date }}</td>
                        <td>{{ message.firstname }}</td>
                        <td>{{ message.lastname }}</td>
                        <td>{{ message.email }}</td>
                        <td>{{ message.phone }}</td>
                        <td>{{ message.message }}</td>
                    </tr>
                {% endfor %}
            </table>

        </div>
      </div>

    {% endblock content %}